- name: installing mongodb
  hosts: mongodb
  become: yes
  tasks:
  - name: copying mongorepo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name: installing mongodb-org
    ansible.builtin.yum:
      name: mongodb-org
      state: installed
  - name: service start and enable
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes
  - name: enable remote connections to the mongodb
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
  - name: restart the mongod service
    ansible.builtin.service:
      name: mongod
      state: restarted

